### ISSUE TITLE
Values ​​are unavailable

### ISSUE THREAD

**Issue by sidwin9** [dolezsa/thermal_comfort#283]
All Thermal Comfort values ​​are unavailable since Home Assistant 2023.3.0 update.

**Comment by iMiMx** [comment]
Upgrading to 2.1.1 - released about 3 hours ago - fixed this issue for me.  Possibly it doesn't show as an upgrade, until you're already on 2023.3.0./

**Comment by ssna** [comment]
Add me with thermal comfort not available on 2023.3.1 after upgrade from 2023.2.?.  Not sure this helps

Logger: homeassistant.components.sensor
Source: custom_components/thermal_comfort/sensor.py:473
Integration: Sensor (documentation, issues)
First occurred: 8:14:18 AM (4 occurrences)
Last logged: 8:14:18 AM

Error while setting up thermal_comfort platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/thermal_comfort/sensor.py", line 470, in async_setup_entry
    entities: list[SensorThermalComfort] = [
  File "/config/custom_components/thermal_comfort/sensor.py", line 473, in <listcomp>
    entity_description=SensorEntityDescription(**SENSOR_TYPES[sensor_type]),
TypeError: SensorEntityDescription.__init__() got an unexpected keyword argument 'native_precision'

**Comment by rautesamtr** [comment]
Same issue you need to update to thermal comfort 2.1.1 and do a restart

**Comment by ssna** [comment]
2.1.1 fixed it.  It wasn't showing as an upgrade when I originally noticed it.  Maybe I didn't check again before posting.
