### ISSUE TITLE
2022.10.x Error deprecation...

### ISSUE THREAD

**Issue by DavidFW1960** [dolezsa/thermal_comfort#202]
```
2022-09-29 10:05:18.209 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for thermal_comfort using this method at custom_components/thermal_comfort/sensor.py, line 604: fahrenheit = util.temperature.celsius_to_fahrenheit(self._temperature)
2022-09-29 10:05:18.211 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for thermal_comfort using this method at custom_components/thermal_comfort/sensor.py, line 626: return round(util.temperature.fahrenheit_to_celsius(hi), 2)
2022-09-29 10:05:18.212 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for thermal_comfort using this method at custom_components/thermal_comfort/sensor.py, line 696: fahrenheit = util.temperature.celsius_to_fahrenheit(self._temperature)
2022-09-29 10:05:18.213 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for thermal_comfort using this method at custom_components/thermal_comfort/sensor.py, line 707: return round(util.temperature.fahrenheit_to_celsius(si), 2)
```

**Comment by rautesamtr** [comment]
Thanks for the report, i guess 2022.4 is a typo and it probably will be removed in 2023.4. We will update to unit_conversion once `pytest-homeassistant-custom-component` moves to 2022.10.

**Comment by Xev** [comment]
But is it though typo in that direction?
In 2022.10.0b0 and 2022.10.0b1 that is the error that occurs:
`Logger: homeassistant.helpers.entity
Source: custom_components/thermal_comfort/sensor.py:604
Integration: Thermal Comfort ([documentation](https://github.com/dolezsa/thermal_comfort/blob/master/README.md), [issues](https://github.com/dolezsa/thermal_comfort/issues))
First occurred: 7:07:04 AM (10 occurrences)
Last logged: 7:19:19 AM

    Update for sensor.*hidden*_comfort_heatindex fails
    Update for sensor.*hidden*_comfort_heatindex fails
    Update for sensor.*hidden*_comfort_heatindex fails
    Update for sensor.*hidden*_comfort_heatindex fails

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
    raise exc
  File "/config/custom_components/thermal_comfort/sensor.py", line 446, in async_update
    value = await getattr(self._device, self._sensor_type)()
  File "/config/custom_components/thermal_comfort/sensor.py", line 261, in wrapped
    setattr(self, f"_{sensor_type}", await func(self, *args, **kwargs))
  File "/config/custom_components/thermal_comfort/sensor.py", line 604, in heat_index
    fahrenheit = util.temperature.celsius_to_fahrenheit(self._temperature)
AttributeError: module 'homeassistant.util' has no attribute 'temperature'`

**Comment by jesserockz** [comment]
I get that `temperature` doesn't even exist already:
```
2022-10-04 13:49:19.837 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.roof_space_simmerzone fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
    raise exc
  File "/config/custom_components/thermal_comfort/sensor.py", line 446, in async_update
    value = await getattr(self._device, self._sensor_type)()
  File "/config/custom_components/thermal_comfort/sensor.py", line 261, in wrapped
    setattr(self, f"_{sensor_type}", await func(self, *args, **kwargs))
  File "/config/custom_components/thermal_comfort/sensor.py", line 712, in simmer_zone
    si = await self.simmer_index()
  File "/config/custom_components/thermal_comfort/sensor.py", line 261, in wrapped
    setattr(self, f"_{sensor_type}", await func(self, *args, **kwargs))
  File "/config/custom_components/thermal_comfort/sensor.py", line 696, in simmer_index
    fahrenheit = util.temperature.celsius_to_fahrenheit(self._temperature)
AttributeError: module 'homeassistant.util' has no attribute 'temperature'
```

**Comment by rautesamtr** [comment]
This is more of an import error, importing the temperature module directly ´from homeassistant.util import temperature´ still works, ´from homeassistant import util´ results in this error.

**Comment by liflitz** [comment]
I get the same WARNING as DavidFW1960 and a reboot takes about 5 times longer than before. I went back to to a restore point from a few days back, installed everything but the latest 1.5.2 to 1.5.3 update: same reboot time as in the past. Finally, doing the thermal comfort update brings back the reboot time extension.

**Comment by riddik14** [comment]
Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for thermal_comfort using this method at custom_components/thermal_comfort/sensor.py, line 604: fahrenheit = temperature.celsius_to_fahrenheit(self._temperature)

**Comment by rautesamtr** [comment]
This will be changed in 2.0 release, please stop re-reporting a deprecation warning. Reporting it once is enough.
