### ISSUE TITLE
2023.12.0.b2 - Setup failed

### ISSUE THREAD

**Issue by pailloM** [dolezsa/thermal_comfort#331]
Works fine with 2023.11.3, but fails with beta release.
Integration fails to setup with following error message:

Logger: homeassistant.setup
Source: setup.py:251
First occurred: 21:59:38 (1 occurrences)
Last logged: 21:59:38

`
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 21:59:38 (1 occurrences)
Last logged: 21:59:38

Setup failed for custom integration 'thermal_comfort': Unable to import component: cannot import name 'async_log_exception' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/thermal_comfort/__init__.py", line 22, in <module>
    from .config import OPTIONS_SCHEMA
  File "/config/custom_components/thermal_comfort/config.py", line 4, in <module>
    from homeassistant.config import async_log_exception, config_without_domain
ImportError: cannot import name 'async_log_exception' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
`

**Comment by pdsccode** [comment]
Core now has a stable release. I did not see this issue here before updating so now I am w/o Thermal Comfort 😢😆

**Comment by wizu** [comment]
me too

**Comment by rautesamtr** [comment]
release is out

**Comment by pailloM** [comment]
Updated the component restarted and all working with 2023.12.0! Good job!
Thanks

**Comment by ajvandr** [comment]
Same error here on 2023.12.1 with a slightly different file ref in the log. 
GMT+10

Logger: homeassistant.setup
Source: setup.py:251
First occurred: 4:07:26 PM (1 occurrences)
Last logged: 4:07:26 PM

Setup failed for custom integration 'thermal_comfort': Unable to import component: cannot import name 'async_log_exception' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/thermal_comfort/__init__.py", line 22, in <module>
    from .config import OPTIONS_SCHEMA
  File "/config/custom_components/thermal_comfort/config.py", line 4, in <module>
    from homeassistant.config import async_log_exception, config_without_domain
ImportError: cannot import name 'async_log_exception' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)

**Comment by ajvandr** [comment]
(facepalm) misunderstood the release comment above.

Sorted now thanks @rautesamtr
