### ISSUE TITLE
Thermal comfort not working with Homeasssitant 2023.12b0 

### ISSUE THREAD

**Issue by yousaf465** [dolezsa/thermal_comfort#325]
![image](https://github.com/dolezsa/thermal_comfort/assets/83491212/0488da28-ecbf-4d0f-b7ad-6a589eb1bb01)

Core
2023.12.0b0
Supervisor
2023.11.6
Operating System
11.2.rc2
Frontend
20231129.1

logs as following 
```
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 12:17:29 (1 occurrences)
Last logged: 12:17:29

Setup failed for custom integration 'thermal_comfort': Unable to import component: cannot import name 'async_log_exception' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/thermal_comfort/__init__.py", line 22, in <module>
    from .config import OPTIONS_SCHEMA
  File "/config/custom_components/thermal_comfort/config.py", line 4, in <module>
    from homeassistant.config import async_log_exception, config_without_domain
ImportError: cannot import name 'async_log_exception' from 'homeassistant.config' (/usr/src/homeassistant/homeassistant/config.py)

```
